# Generated by Django 3.1.7 on 2021-07-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='encuesta',
        ),
        migrations.DeleteModel(
            name='respuesta',
        ),
    ]
