# Generated by Django 3.1.7 on 2021-09-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210824_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['id'], 'verbose_name': 'encuesta', 'verbose_name_plural': 'encuestas'},
        ),
        migrations.AddField(
            model_name='encuesta',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='eleccion',
            field=models.IntegerField(null=True),
        ),
    ]
