# Generated by Django 3.1.7 on 2021-09-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210908_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
