# Generated by Django 3.1.7 on 2021-09-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='centro_trabajo',
            field=models.CharField(choices=[('PK001', 'Oficina sede de la GRTSE'), ('PK0A0', 'zona de transmision villa hermosa')], default='PK001', max_length=100),
        ),
    ]
