# Generated by Django 3.1.7 on 2021-09-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210921_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='centro_trabajo',
            field=models.CharField(choices=[('PK001', 'Oficina sede de la GRTSE'), ('PK0A0', 'Zona de transmisión Villahermosa'), ('PK0B0', 'Zona de transmisión Tuxtla'), ('PK0C0', 'Zona de transmisión Tapachula'), ('PK0D0', 'Zona de transmisión Istmo'), ('PK0E0', 'Zona de transmisión Malpaso'), ('PK0F0', 'Zona de operación de transmisión STE'), ('PK0A1', 'Zona de transmisión Villahermosa sector Chontalpa'), ('PK0B1', 'Zona de transmisión Tuxtla sector Chicoasén'), ('PK0B2', 'Zona de transmisión Tuxtla sector Angostura'), ('PK0D1', 'Zona de transmisión Istmo sector Oaxaca potencia'), ('PK0E1', 'Zona de transmisión Malpaso sector Peñitas')], default='PK0E0', max_length=100),
        ),
    ]
