# Generated by Django 3.1.7 on 2021-10-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210925_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contesto', models.BooleanField(null=True)),
                ('atencion_clinica', models.BooleanField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.empleado')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultado',
                'db_table': 'resultado',
            },
        ),
    ]
