# Generated by Django 3.1.7 on 2021-10-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20211004_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='contesto',
        ),
        migrations.AddField(
            model_name='resultado',
            name='cat1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='cat2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='cat3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='cat4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='cat5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='dom9',
            field=models.IntegerField(null=True),
        ),
    ]
