# Generated by Django 3.1.7 on 2021-10-07 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20211004_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='contestado',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 7, 2, 5, 3, 71471, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
